environment:
  ANDROID_HOME: C:\Program Files (x86)\Android\android-sdk

install:
  # - dir C:\Program Files (x86)\Android\android-sdk
  # - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all --filter android-25
  - cmd: dir C:\Program^ Files^ (x86)\Android\android-sdk
  # - echo y | "%ANDROID_HOME%\tools\android.bat" --silent update sdk --no-ui --all
  # - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t tools, build-tools-25.0.0
  # - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk -u -a -t platform-tools, extra-android-m2repository

test_script:
  - gradlew.bat build

build: off